% MATLAB Editor Run Commands
% @version 3
% It is recommended that you do not edit this file directly, but use the
% Run button. Changes made to comments that exist outside of a
% configuration will not be saved.

%% @name cosinus
%  @associatedFile U:\teme\cosinus.m
%  @mostRecentlyActioned true
%  @uniqueId -77e2cec9:1628fee9613:-7dc6

cosinus(x, err)

