M7R0
I3DividedDifferencesf*6$'%"xG%%listG'%"yGF'6&%"iG%"jG%"nG%$DDTG6"F/C'>8&-%%nops
G6#9$>8'-%'MatrixG6$F2F2?(8$"""F>F2%%trueG>&F86$F=F>&9%6#F=?(F=F>F>F2F??(8%F>F>
,&F2F>F=!""F?>&F86$FH,&F=F>F>F>*&,&&F86$,&FHF>F>F>F=F>&F86$FHF=FJF>,&&F66#,&FHF
>F=F>F>&F66#FHFJFJOF86#QBcompute~divided~differences~tableF/F/F/F/,
I5MNDividedDifferencesf*6$F%'%#fdG-F'6#F'6,%#lxG%#szG%"kGF,%"zG%#tdG%#icG%#ldG%
$tvdG%#ppGF/F/C,&FD6#F>>F=F3>8+-%$mapG6$F4FD>FH-%$addG6$F+/F+F_p>8)-F:6%FHFHf*6
$F+F,F/6$%)operatorG%&arrowGF/%*undefinedGF/F/F/>8(7">8*F>?(F2F>F>F=F?C%>8,&FD6
#F2?(F8F>F>&F_pF\rF?C$?(8-F>F>,(F^rF>F8FJF>F>F?>&Fip6$FfqFar&Fjq6#Far>Ffq,&FfqF
>F>F>>Fcq7$-%#opG6#Fcq-%"$G6$&F6F\rF^r?(F2""#F>FHF??(F8F>F>,(FHF>F2FJF>F>F?@$-%
%typeG6$&Fip6$F8F2Faq>F[t*&,&&Fip6$,&F8F>F>F>,&F2F>FJF>F>&Fip6$F8FctFJF>,&&Fcq6
#,(F8F>F2F>FJF>F>&Fcq6#F8FJFJO6$FcqFip6#QVcompute~divided~differences~table~wit
h~multiple~nodesF/F/F/F/,
I+NewtonPolyf*6%'F.F:'FdoF''%"tG%%nameG6$F-%"sGF/F/C$>F=-F46#FD>FH,&&F66$F>F>F>
-Fep6$*&&F66$F>FcoF>-%$mulG6$,&9&F>&FD6#F,FJ/F,;F>,&FcoF>FJF>F>/Fco;FdsF=F>6#Q:
compute~Newton~PolynomialF/F/F/F/,
I1NewtonPolynomialf*6%F%F(Feu6$Feo%"PGF/F/C$>F=-F"6$F6FD>FH-F`u6%F=F6F[wFcwF/F/
F/,
I8NewtonHermitePolynomialf*6%F%F\oFeu6%FeoFdoFiwF/F/C$>FU-FinF]x>F2-F`u6%F=FHF[
wF/F/F/F/
